Repository redBorder/cookbook-rb-proxy, pull requests merged in 2024-05, with the labels that each got.

#21 exclude chef-client from memservice
  resources/attributes/default.rb
  resources/libraries/memory_services.rb
  resources/recipes/prepare_system.rb
Labels: bug, size/M

#22 Release 0.1.6
  CHANGELOG.md
  resources/attributes/default.rb
  resources/libraries/memory_services.rb
  resources/metadata.rb
  resources/recipes/prepare_system.rb
Labels: size/M, kind/documentation

#23 Add configure common cookbook call
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: kind/feature, size/XS, feature

#24 Release 0.2.0
  CHANGELOG.md
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S, kind/documentation

#26 Add full kernel release info in motd
  resources/templates/default/motd.erb
Labels: size/XS, kind/documentation

#25 Bug/#17404 rb exporter status in rb cli
  resources/attributes/default.rb
Labels: size/XS, kind/bug

#27 Release 0.2.1
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/templates/default/motd.erb
Labels: size/S, kind/documentation
