Repository redBorder/cookbook-rb-proxy, pull requests merged in 2024-04, with the labels that each got.

#16 add k2http to rb-proxy
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S, kind/documentation

#17 Release 0.1.4
  resources/metadata.rb
Labels: size/XS, kind/documentation

#18 Added ../rpm.yml to .github/workflows/
  .github/workflows/rpm.yml
Labels: size/M

#19 add rb_exporter service in redborder proxy
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/XS

#20 Release 0.1.5
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: size/S, kind/documentation
