Repository redBorder/cookbook-rb-proxy, pull requests merged in 2024-06, with the labels that each got.

#28 add temporary variables in node.run_state
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: kind/feature, size/M

#29 Release 0.2.2
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/M, kind/documentation

#30 Bugfix/#15141 remove geoip from service list
  resources/attributes/default.rb
  resources/recipes/configure.rb
Labels: size/XS, kind/bug

#31 Release 0.2.3
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: bug, size/S, kind/documentation, release

#33 Release 0.2.4
  CHANGELOG.md
  resources/attributes/default.rb
  resources/libraries/get_namespaces.rb
  resources/libraries/get_orgs.rb
  resources/libraries/get_sensors_all_info.rb
  resources/libraries/get_sensors_info.rb
  resources/libraries/in_hash.rb
  resources/libraries/memory_services.rb
  resources/libraries/proxy_services.rb
  resources/libraries/util.rb
  resources/metadata.rb
  resources/recipes/configure.rb
  resources/recipes/configure_journald.rb
  resources/recipes/default.rb
  resources/recipes/prepare_system.rb
  resources/templates/default/sysconfig_chef-client.rb.erb
Labels: kind/documentation, size/XL

#35 disable freeradius
  resources/attributes/default.rb
Labels: size/XS

#36 Release 0.2.5
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
Labels: size/XS, kind/documentation

#37 Add clamAV
  resources/attributes/default.rb
  resources/metadata.rb
  resources/recipes/configure.rb
Labels: kind/feature, size/XS

#34 Bugfix/17238 logstash not running when no pipelines
  resources/attributes/default.rb
  resources/libraries/get_monitor_configuration.rb
  resources/libraries/get_pipelines.rb
  resources/recipes/configure.rb
  resources/recipes/prepare_system.rb
Labels: size/M, kind/bug
